<a href="https://colab.research.google.com/github/joiepark/assignment_esaa/blob/main/YB%201.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
import numpy as np
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
list1 = [1, 2, 3, 4, 5]
array1 = np.array(list1)
print(array1.dtype)

int64


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector1 = np.arange(start=10, stop=50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector2 = [1, 2, 3, 4, 5]
reverse_vector = np.flip(vector2)
print(reverse_vector)

[5 4 3 2 1]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
array8a = np.arange(9)
array8b = array8a.reshape(3, 3)
print(array8b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
array9 = np.array([1,2,0,0,4,0])
print(np.nonzero(array9)[0])

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [18]:
array10 = np.identity(3)
print(array10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [20]:
array11 = np.random.random((3, 3, 3))
print(array11)

[[[0.76807646 0.69933224 0.07284455]
  [0.4861733  0.15864457 0.21484341]
  [0.13286607 0.95820556 0.63672818]]

 [[0.56357743 0.5892265  0.62398349]
  [0.15484598 0.99336066 0.35669534]
  [0.01181137 0.01730979 0.60748411]]

 [[0.73632385 0.06172162 0.25957018]
  [0.93641878 0.36046311 0.20397523]
  [0.88793949 0.28864755 0.26954702]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [21]:
array12 = np.random.random((10, 10))
print(array12)
max_value = np.max(array12)
min_value = np.min(array12)
print(max_value, min_value)

[[0.46193    0.87455358 0.6301232  0.7505091  0.5792218  0.55218256
  0.94220595 0.2462643  0.28340526 0.94286528]
 [0.77521292 0.54633498 0.28422087 0.95311483 0.74706635 0.50400261
  0.90049041 0.12770888 0.53976564 0.89987046]
 [0.7805353  0.63554378 0.18015154 0.22665409 0.25016587 0.31342599
  0.51777071 0.13373376 0.41781924 0.15621221]
 [0.56158677 0.67924719 0.354134   0.15241137 0.72771534 0.3578867
  0.90144759 0.35411835 0.04661385 0.65163858]
 [0.63151345 0.78385114 0.10596557 0.45190255 0.39142962 0.76691589
  0.63325083 0.64065254 0.97553844 0.06061342]
 [0.94635706 0.21284194 0.77292438 0.87966017 0.89169313 0.02267478
  0.44987398 0.51358987 0.23121738 0.39507683]
 [0.01114766 0.15018001 0.93376586 0.83030042 0.15612185 0.82840643
  0.17823709 0.10639081 0.08138899 0.46468908]
 [0.66229016 0.20805485 0.98392672 0.61112159 0.79685947 0.24185659
  0.70885165 0.46877722 0.99881378 0.23317673]
 [0.33983278 0.9933831  0.42485674 0.57679523 0.46546856 0.30960663
  0.09965718 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [23]:
array13 = np.random.random(30)
print(array13)
mean_value = np.mean(array13)
print(mean_value)

[0.33984699 0.04838416 0.99218745 0.52851567 0.30682095 0.74383552
 0.99033935 0.83924704 0.77415528 0.20653953 0.69127888 0.34332367
 0.6236944  0.4317423  0.90462143 0.67248898 0.35936824 0.63257137
 0.95999142 0.33977159 0.74622858 0.76982351 0.84075822 0.60559786
 0.05270884 0.07898202 0.49882736 0.68645254 0.11593586 0.39136662]
0.5505135216299082


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [22]:
array14 = np.ones((5, 5))
array14[1:-1, 1:-1] = 0
print(array14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [25]:
array16 = np.zeros((5, 5))
np.fill_diagonal(array16[1:], [1, 2, 3, 4])
print(array16)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [26]:
array17 = np.zeros(((8, 8)))
array17[1::2, ::2] = 1
array17[::2, 1::2] = 1
print(array17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [8]:
print(np.unravel_index(100, (6, 7, 8)))

(np.int64(1), np.int64(5), np.int64(4))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [9]:
array19 = np.random.random((5, 5))
mean = np.mean(array19)
std = np.std(array19)
print(array19)

[[0.59047467 0.06522161 0.49918238 0.78599142 0.7700753 ]
 [0.24799919 0.81644268 0.74834974 0.92848036 0.63042158]
 [0.86002123 0.64394894 0.93617746 0.98983406 0.82497984]
 [0.39553837 0.93938777 0.10783094 0.42601604 0.26367765]
 [0.44321007 0.62301472 0.23188353 0.52889397 0.44541708]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [11]:
array20 = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(array20)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
